version: '3.8'

services:
  kure-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - DEFAULT_MODEL=nlpai-lab/KURE-v1
      - MAX_BATCH_SIZE=32
      - MAX_TEXT_LENGTH=8192
    volumes:
      - model_cache:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  model_cache:
